# Generated by Django 4.2.19 on 2025-03-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_cart_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='img')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('level', models.IntegerField(default=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
