# Generated by Django 4.2.19 on 2025-03-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_product_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
