# Generated by Django 4.2.19 on 2025-03-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_product_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
    ]
